### ISSUE TITLE
Thank you so very much. :)

### ISSUE THREAD

**Issue by kreezxil** [michaelprograms/fluffos-tutorial#2]
I've been looking to get back into mudding and finding a mudlib and driver that are designed for each others with little to no extra tweaks to get started has been the hardest thing to do since the early 2000s. Probably my old brain is at fault. But thanks to your efforts, I was able to pull it off, easy-peasy lemon-squeezy.

If you're from the early days of mudding circa 1992 through 1998, you know me as Trimaster.

**Comment by michaelprograms** [comment]
Glad you are able to get back into it! :) And many thanks to [CPU's LDMud Tutorial](https://github.com/cpu/ldmud-tutorial) for lighting the way..

**Comment by kreezxil** [comment]
offhand do you know if your mudlib from this repo supports FTP for creators? if not do you have a recommendation for how to do that or something similar. The inbuilt editing is archaic as it would be far easier to upload something edited locally.

**Comment by kreezxil** [comment]
btw, i'm getting issues where these warnings are constantly being printed. Thought it was being broadcast on the error line but it wasn't. Is there a way to turn them off?

```
/lib/virtual/virt_land.c line 12: Warning: Redeclaration of global variable 'Search'. before the
end of line

/lib/virtual/virt_land.c line 76: Warning: Number of arguments disagrees with previous definition.
before {

/lib/virtual/virt_land.c line 76: Warning: Function SetCoordinates inherited from '/lib/std/room.c'
does not match current function in return type ( string vs void ) before {

/lib/virtual/virt_sky.c line 15: Warning: Redeclaration of global variable 'counter'. before the
end of line

/lib/virtual/virt_sky.c line 15: Warning: Redeclaration of global variable 'Search'. before the end
of line

/lib/virtual/virt_sky.c line 90: Warning: Value of conditional expression is unused before (
exit["post"] ){

/lib/virtual/virt_subsurface.c line 7: Warning: Redeclaration of global variable 'counter'. before
the end of line

/lib/virtual/virt_subsurface.c line 7: Warning: Redeclaration of global variable 'Search'. before
the end of line

/secure/lib/connect.c line 365: Warning: Unknown \ escape. before k, allowing default 

/secure/daemon/players.c line 43: Warning: Redeclaration of global variable 'InternalDesc'. before 
WebPage, Clan;
```

**Comment by kreezxil** [comment]
it's not just those, all kinds of things are throwing them, the mud works fine tho.

**Comment by kreezxil** [comment]
Ok, I found a solution. If there's an easier solution, please let me know. What I had to do was modify the local_options file that is located at the top, where run.sh and build.sh are located. And removed PRAGMA_WARNINGS. Recompile the driver and restart the mud.

**Comment by michaelprograms** [comment]
> offhand do you know if your mudlib from this repo supports FTP for creators? if not do you have a recommendation for how to do that or something similar. The inbuilt editing is archaic as it would be far easier to upload something edited locally.

nightmare3 doesn't support FTP out of the box, I've only seen a few that do and they aren't very popularly used.

**Comment by michaelprograms** [comment]
> Ok, I found a solution. If there's an easier solution, please let me know. What I had to do was modify the local_options file that is located at the top, where run.sh and build.sh are located. And removed PRAGMA_WARNINGS. Recompile the driver and restart the mud.

Yeah, this was a newer pragma added to fluffos a while back. Generally the solution is to disable it or fix all the warnings. :)

**Comment by kreezxil** [comment]
after staring at the plethora of commands Nightmare has, I saw this in the mudconfig

![image](https://github.com/michaelprograms/fluffos-tutorial/assets/3880072/d8f2cc56-6cd6-4d95-8d35-0c0b39c0467a)

I'm wondering if that does what I want, is there documentation on it? In fact is there documentation on any of the commands under **mudconfig**? 

Thanks for all your help.

**Comment by kreezxil** [comment]
Alright after digging and paying even more attention to the screen like I did way back in 1992, I saw where I can get my answers. I'll close the comment now. Hopefully others digging around will find my thoughts to be helpful to them.

http://dead-souls.net/ds-admin-faq.html

**Comment by cpu** [comment]
@kreezxil If you're a Discord user there's a small community of LPC programmers that hang out in [this server](https://discord.gg/mtxcJUFB). You're also welcome to join and ask questions there!

**Comment by kreezxil** [comment]
michael I found an issue with the spells.c daemon in the ds3 lib. I was getting a string vs mixed error. The solution was to change the declaration
```
string* spells, prayers;
```
to
```
string *spells, *prayers;
```
I had to use gpt to figure it out. https://chat.openai.com/share/0efc6913-4716-4bb3-83cb-7140de91749f

**Comment by michaelprograms** [comment]
> string *spells, *prayers;

:+1: You should contribute this back to the https://github.com/fluffos/dead-souls/ repository! :)

**Comment by kreezxil** [comment]
done, here's the pr: https://github.com/fluffos/dead-souls/pull/11
